AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80
  Exclude:
    - h3m.gemspec

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10